
      FUNCTION C1(ALPHA,GINV)
C     FUNCTION DEFINED BY HIRSHMAN AND SIGMAR EQ. 6.72

      IMPLICIT NONE

      REAL*8 C1, ALPHA, GINV

      C1 = 1. - 0.52*ALPHA/(0.59+ALPHA+1.34*GINV**2)

      RETURN 
      END
