 test.o : test.f
 test1.o : test1.f
 test2.o : test2.f
 test3.o : test3.f
 test4.o : test4.f
 test5.o : test5.f
 test6.o : test6.f
 test7.o : test7.f
 test8.o : test8.f
 test9.o : test9.f
 test10.o : test10.f
 test11.o : test11.f
 c1.o : c1.f
 c2.o : c2.f
 c3.o : c3.f
 k22.o : k22.f
 test12.o : test12.f
 test13.o : test13.f
 test14.o : test14.f
 test15.o : test15.f
 psflux.o : psflux.f
 test16.o : test16.f
 ralf.o : ralf.f
 test17.o : test17.f
 dandv.o : dandv.f
 zzz000.o : zzz000.f
 ps.o : ps.f
 bp.o : bp.f
 viscos.o : viscos.f
 visfus.o : visfus.f
 viscol.o : viscol.f
 menn.o : menn.f
 penq.o : penq.f
 colxi.o : colxi.f
 perr.o : perr.f
 geom.o : geom.f
 circgeom.o : circgeom.f
 visgeom.o : visgeom.f
 erf.o : erf.f
 ludcmp.o : ludcmp.f
 lubksb.o : lubksb.f
 get_geom.o : get_geom.f
 advance.o : advance.f
 interp.o : interp.f
