
      FUNCTION K22(ALPHA,OMTH,OMTI,M1,M2,ZSP1,ZSP2)
C     THIS FUNCTION CALCULATES THE HEAT FLUX OF THE IMPURITY TAKING 
C     INTO ACCOUNT THE HEAT COUPLING. THE ANALYTIC FUCTION OF 
C     HIRSMANN AND SIGMAR (6.113) IS PROGRAMED. K22 IS HOWEVER 
C     NORMALIZED K22 = K22(6.113) / TAU(I,I)

C     INPUT
C     ALPHA = N_I Z_I^2 / N_H Z_H^2
C     OMTH  = OMEGA_H TAU_HH  (SEE THE TEXT AROUND 6.70)
C     OMTI  = OMEGA_I TAU_II
C     M1    = HYDROGEN MASS
C     M2    = IMPURITY MASS
C     ZSP1  = HYDROGEN CHARGE 
C     ZSP2  = IMPURITY CHARGE
      IMPLICIT NONE

      REAL*8 ALPHA, OMTH, OMTI, XI, XIS, M1, M2,  C3, K22
      REAL*8 ZSP1, ZSP2

      XI  = SQRT(M1/M2) / (OMTI**2*ALPHA)
      XIS = SQRT(M2/M1) * ALPHA * ZSP2/ ZSP1  * C3(0.D0,OMTI)/
     +      C3(ALPHA,OMTH)

      K22 = C3(0.D0,OMTI)*(1.+ XI/XIS)/(1.+ XI)
   
      RETURN 
      END
