      SUBROUTINE TEST2
C-----------------------------------------------------------------
C     CALCULATE THE TRANSPORT COEFFICIENTS IN THE P.S. REGIME 
C     FOR A SIMPLE HYDROGEN PLASMA AND COMPARE THEM WITH THE 
C     VALUES GIVEN IN THE LITERATURE.
C-----------------------------------------------------------------
      IMPLICIT NONE

      INTEGER NS,NC,NAR,ISEL,NREG,NLEG,NENERGY,NCOF,
     +        IC,NZM,I,J,NMAXGR,ISHOT
      REAL M,T,DEN,DS,CFF1,CFF2,CFF3,CFF4,XI,TAU,
     +       EPS, SIGMA, NORM, ZSP, EPARR 
      REAL RHO, RN, E, Q, BN
      LOGICAL NEOGEO, NEOFRC

      include 'elem_config.inc'
      
      parameter(NAR = NELMAX+2)
      parameter(NZM = NIONMAX)
      PARAMETER(NMAXGR = 1000)

      DIMENSION NC(NAR),ZSP(NAR,NZM),M(NAR),T(NAR),DEN(NAR,NZM),
     +          DS(NAR,NZM,2),CFF1(NAR,NZM,4),CFF2(NAR,NZM,4),
     +          CFF3(NAR,NZM,4),CFF4(NAR,NZM,4),XI(NAR,NZM),
     +          TAU(NAR,NAR),SIGMA(4)


C     SET THE PARAMETERS FOR THE CIRCULAR GEOMETRY
      RHO = 0.05
      E = 1E-4
      Q = 1/SQRT(2.)
      RN = 1.65
      BN = 2.5
      ISHOT = 0
C     SET THE ELECTRIC FIELD TO ZERO 
      EPARR = 0. 
C     COPY THEM INTO THE VALUES USED BY THE CODE
      CALL CIRCGEOM(1,RHO,RN,E,Q,BN)
C     USE THE CIRCULAR GEOMETRY APPROXIMATION
      ISEL = 2
C     SET THE ACCURACY
      EPS = 1E-5
C     SWITCH OFF ION-ELECTRON COLLISIONS
      NCOF = 0
C     IN THE FIRST CALL THE MATRICES HAVE TO BE CALCULATED
      NEOFRC = .FALSE.
C     CALCULATE THE P.S. CONTRIBUTION
      IC = 2

C     THE NUMBER OF SPECIES IS 2
      NS = 2
C     IONS AND ELECTRONS HAVE ONLY ONE CHARGE 
      NC(1) = 1
      NC(2) = 1
C     THE MASS OF THE ELECTRON AND PROTON
      M(1) = 9.1096E-31
      M(2) = 1.6727E-27
C     THE CHARGE OF THE ELECTRON AND ION
      ZSP(1,1) = -1
      ZSP(2,1) = 1
C     THE DENSITY OF THE SPECIES IN 10^19 M^-3
      DEN(1,1) = 7.
      DEN(2,1) = 7. 
C     THE TEMPERATURE IN KEV
      T(1) = 0.001
      T(2) = 0.001
C     FORCE THE COLLISION LESS REGIME (NEGLECT ALL COUPLINGS)
      SIGMA(1) = 0
      SIGMA(2) = 0
      SIGMA(3) = 0
      SIGMA(4) = 0 

C     RECALCULATE THE GEOMETRY PARAMETERS 
      NEOGEO = .TRUE. 

C     THE THERMODYNAMIC FORCES
      DO 201 I = 1, NS
        DO 201 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 201  CONTINUE
      DS(1,1,1) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF1)

C     AFTER THE FIRST CALL IT IS NOT NECESSARY TO RECALCULTE
C     THE MATRICES
      NEOFRC = .TRUE.

      DO 202 I = 1, NS
        DO 202 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 202  CONTINUE
      DS(2,1,1) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF2)

      DO 203 I = 1, NS
        DO 203 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 203  CONTINUE
      DS(1,1,2) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF3)

      DO 204 I = 1, NS
        DO 204 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 204  CONTINUE
      DS(2,1,2) = 1.


      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF4)


      CALL COLXI(NAR,NZM,NS,NC,ZSP,DEN,T,M,TAU,XI)

      NORM = 1.6E-22*BN**2/(4*(Q)**2
     +       *T(2)*TAU(2,2))

      WRITE(*,*)'**** THE COLLISION LESS PS FLUXES '
      WRITE(*,1000)'THE ION HEAT FLUX                 '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +    SQRT(2.)*CFF4(2,1,2)*NORM,'SHOULD BE -1.00'
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +    SQRT(2.)*CFF3(2,1,2)*NORM
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +    SQRT(2.)*CFF2(2,1,2)*NORM
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +    SQRT(2.)*CFF1(2,1,2)*NORM

      NORM = 1.6E-22*BN**2/(4*(Q)**2
     +       *T(1)*TAU(1,2))

      WRITE(*,*)
      WRITE(*,1000)'THE ELECTRON HEAT FLUX            '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +   CFF4(1,1,2)*NORM
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +   CFF3(1,1,2)*NORM,'SHOULD BE -2.33'
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +   CFF2(1,1,2)*NORM,'SHOULD BE  0.75'
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +   CFF1(1,1,2)*NORM,'SHOULD BE  0.75'

      WRITE(*,*)
      WRITE(*,1000)'THE PARTICLE FLUX                 '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +    CFF4(1,1,1)*NORM
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +    CFF3(1,1,1)*NORM,'SHOULD BE  0.75'
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +    CFF2(1,1,1)*NORM,'SHOULD BE -0.50'
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +    CFF1(1,1,1)*NORM,'SHOULD BE -0.50'

C     THE DEEP PFIRSCH SCHLUETER REGIME WITHOUT ENERGY COUPL.
      SIGMA(1) = 0
      SIGMA(2) = 0
      SIGMA(3) = 0
      SIGMA(4) = 1 
c     RECALCULATE THE MATRICES
      NEOFRC = .FALSE.

C     THE THERMODYNAMIC FORCES
      DO 301 I = 1, NS
        DO 301 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 301  CONTINUE
      DS(1,1,1) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF1)

C     AFTER THE FIRST CALL IT IS NOT NECESSARY TO RECALCULTE
C     THE MATRICES
      NEOFRC = .TRUE.

      DO 302 I = 1, NS
        DO 302 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 302  CONTINUE
      DS(2,1,1) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF2)

      DO 303 I = 1, NS
        DO 303 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 303  CONTINUE
      DS(1,1,2) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF3)

      DO 304 I = 1, NS
        DO 304 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 304  CONTINUE
      DS(2,1,2) = 1.


      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF4)


      CALL COLXI(NAR,NZM,NS,NC,ZSP,DEN,T,M,TAU,XI)

      NORM = 1.6E-22*BN**2/(4*(Q)**2
     +       *T(2)*TAU(2,2))

      WRITE(*,*)'**** THE COLLISIONAL PS FLUXES Z = 1'
      WRITE(*,1000)'THE ION HEAT FLUX                 '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +    SQRT(2.)*CFF4(2,1,2)*NORM,'SHOULD BE -0.80'
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +    SQRT(2.)*CFF3(2,1,2)*NORM
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +    SQRT(2.)*CFF2(2,1,2)*NORM
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +    SQRT(2.)*CFF1(2,1,2)*NORM

      NORM = 1.6E-22*BN**2/(4*(Q)**2
     +       *T(1)*TAU(1,2))

      WRITE(*,*)
      WRITE(*,1000)'THE ELECTRON HEAT FLUX            '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +   CFF4(1,1,2)*NORM
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +   CFF3(1,1,2)*NORM,'SHOULD BE -0.98'
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +   CFF2(1,1,2)*NORM,'SHOULD BE  0.27'
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +   CFF1(1,1,2)*NORM,'SHOULD BE  0.27'

      WRITE(*,*)
      WRITE(*,1000)'THE PARTICLE FLUX                 '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +    CFF4(1,1,1)*NORM
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +    CFF3(1,1,1)*NORM,'SHOULD BE  0.27'
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +    CFF2(1,1,1)*NORM,'SHOULD BE -0.33'
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +    CFF1(1,1,1)*NORM,'SHOULD BE -0.33'

c     DO THE Z = 2 CASE
      ZSP(2,1) = 2
      DEN(2,1) = DEN(1,1) / ZSP(2,1)

c     RECALCULATE THE MATRICES
      NEOFRC = .FALSE.


C     THE THERMODYNAMIC FORCES
      DO 401 I = 1, NS
        DO 401 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 401  CONTINUE
      DS(1,1,1) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF1)

C     AFTER THE FIRST CALL IT IS NOT NECESSARY TO RECALCULTE
C     THE MATRICES
      NEOFRC = .TRUE.

      DO 402 I = 1, NS
        DO 402 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 402  CONTINUE
      DS(2,1,1) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF2)

      DO 403 I = 1, NS
        DO 403 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 403  CONTINUE
      DS(1,1,2) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF3)

      DO 404 I = 1, NS
        DO 404 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 404  CONTINUE
      DS(2,1,2) = 1.


      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF4)


      CALL COLXI(NAR,NZM,NS,NC,ZSP,DEN,T,M,TAU,XI)

      NORM = 1.6E-22*BN**2/(4*(Q)**2
     +       *T(2)*TAU(2,2))

      WRITE(*,*)'**** THE COLLISIONAL PS FLUXES Z = 2'
      WRITE(*,1000)'THE ION HEAT FLUX                 '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +    SQRT(2.)*CFF4(2,1,2)*NORM
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +    SQRT(2.)*CFF3(2,1,2)*NORM
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +    SQRT(2.)*CFF2(2,1,2)*NORM
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +    SQRT(2.)*CFF1(2,1,2)*NORM

      NORM = 1.6E-22*BN**2/(4*(Q)**2
     +       *T(1)*TAU(1,2))

      WRITE(*,*)
      WRITE(*,1000)'THE ELECTRON HEAT FLUX            '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +   CFF4(1,1,2)*NORM
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +   CFF3(1,1,2)*NORM,'SHOULD BE -0.64'
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +   ZSP(2,1)*CFF2(1,1,2)*NORM,'SHOULD BE  0.23'
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +   CFF1(1,1,2)*NORM,'SHOULD BE  0.23'

      WRITE(*,*)
      WRITE(*,1000)'THE PARTICLE FLUX                 '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +    CFF4(1,1,1)*NORM
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +    CFF3(1,1,1)*NORM,'SHOULD BE  0.23'
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +    ZSP(2,1)*CFF2(1,1,1)*NORM,'SHOULD BE -0.31'
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +    CFF1(1,1,1)*NORM,'SHOULD BE -0.31'

c     DO THE Z = 4 CASE
      ZSP(2,1) = 4
      DEN(2,1) = DEN(1,1) / ZSP(2,1)

c     RECALCULATE THE MATRICES
      NEOFRC = .FALSE.


C     THE THERMODYNAMIC FORCES      
      DO 501 I = 1, NS
        DO 501 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 501  CONTINUE
      DS(1,1,1) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF1)

C     AFTER THE FIRST CALL IT IS NOT NECESSARY TO RECALCULTE
C     THE MATRICES
      NEOFRC = .TRUE.

      DO 502 I = 1, NS
        DO 502 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 502  CONTINUE
      DS(2,1,1) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF2)

      DO 503 I = 1, NS
        DO 503 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 503  CONTINUE
      DS(1,1,2) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF3)

      DO 504 I = 1, NS
        DO 504 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 504  CONTINUE
      DS(2,1,2) = 1.


      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF4)


      CALL COLXI(NAR,NZM,NS,NC,ZSP,DEN,T,M,TAU,XI)

      NORM = 1.6E-22*BN**2/(4*(Q)**2
     +       *T(2)*TAU(2,2))

      WRITE(*,*)'**** THE COLLISIONAL PS FLUXES Z = 4'
      WRITE(*,1000)'THE ION HEAT FLUX                 '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +    SQRT(2.)*CFF4(2,1,2)*NORM
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +    SQRT(2.)*CFF3(2,1,2)*NORM
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +    SQRT(2.)*CFF2(2,1,2)*NORM
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +    SQRT(2.)*CFF1(2,1,2)*NORM

      NORM = 1.6E-22*BN**2/(4*(Q)**2
     +       *T(1)*TAU(1,2))

      WRITE(*,*)
      WRITE(*,1000)'THE ELECTRON HEAT FLUX            '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +   CFF4(1,1,2)*NORM
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +   CFF3(1,1,2)*NORM,'SHOULD BE -0.45'
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +   ZSP(2,1)*CFF2(1,1,2)*NORM,'SHOULD BE  0.19'
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +   CFF1(1,1,2)*NORM,'SHOULD BE  0.19'

      WRITE(*,*)
      WRITE(*,1000)'THE PARTICLE FLUX                 '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +    CFF4(1,1,1)*NORM
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +    CFF3(1,1,1)*NORM,'SHOULD BE  0.19'
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +    ZSP(2,1)*CFF2(1,1,1)*NORM,'SHOULD BE -0.28'
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +    CFF1(1,1,1)*NORM,'SHOULD BE -0.28'

c     DO THE Z >>1 CASE
      ZSP(2,1) = 1000
      DEN(2,1) = DEN(1,1) / ZSP(2,1)

c     RECALCULATE THE MATRICES
      NEOFRC = .FALSE.


C     THE THERMODYNAMIC FORCES
      DO 601 I = 1, NS
        DO 601 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 601  CONTINUE
      DS(1,1,1) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF1)

C     AFTER THE FIRST CALL IT IS NOT NECESSARY TO RECALCULTE
C     THE MATRICES
      NEOFRC = .TRUE.

      DO 602 I = 1, NS
        DO 602 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 602  CONTINUE
      DS(2,1,1) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF2)

      DO 603 I = 1, NS
        DO 603 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 603  CONTINUE
      DS(1,1,2) = 1.

      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF3)

      DO 604 I = 1, NS
        DO 604 J = 1, NC(I)
          DS(I,J,1) = 0.
          DS(I,J,2) = 0.
 604  CONTINUE
      DS(2,1,2) = 1.


      CALL NEOART(NS,NC,NAR,NZM,ZSP,M,T,DEN,DS,RHO,EPS,
     +            ISEL,ISHOT,NREG,SIGMA,NLEG,NENERGY,NCOF,
     +            NEOGEO,NEOFRC,IC,EPARR,CFF4)


      CALL COLXI(NAR,NZM,NS,NC,ZSP,DEN,T,M,TAU,XI)

      NORM = 1.6E-22*BN**2/(4*(Q)**2
     +       *T(2)*TAU(2,2))

      WRITE(*,*)'**** THE COLLISIONAL PS FLUXES Z >>1'
      WRITE(*,1000)'THE ION HEAT FLUX                 '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +    SQRT(2.)*CFF4(2,1,2)*NORM
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +    SQRT(2.)*CFF3(2,1,2)*NORM
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +    SQRT(2.)*CFF2(2,1,2)*NORM
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +    SQRT(2.)*CFF1(2,1,2)*NORM

      NORM = 1.6E-22*BN**2/(4*(Q)**2
     +       *T(1)*TAU(1,2))

      WRITE(*,*)
      WRITE(*,1000)'THE ELECTRON HEAT FLUX            '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +   CFF4(1,1,2)*NORM
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +   CFF3(1,1,2)*NORM,'SHOULD BE -0.25'
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +   ZSP(2,1)*CFF2(1,1,2)*NORM,'SHOULD BE  0.15'
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +   CFF1(1,1,2)*NORM,'SHOULD BE  0.15'

      WRITE(*,*)
      WRITE(*,1000)'THE PARTICLE FLUX                 '
      WRITE(*,1000)'ION TEMPERATURE GRADIENT          ',
     +    CFF4(1,1,1)*NORM
      WRITE(*,1000)'ELECTRON TEMPERATURE GRADIENT     ',
     +    CFF3(1,1,1)*NORM,'SHOULD BE  0.15'
      WRITE(*,1000)'ION PRESSURE GRADIENT             ',
     +    ZSP(2,1)*CFF2(1,1,1)*NORM,'SHOULD BE -0.24'
      WRITE(*,1000)'ELECTRON PRESSURE GRADIENT        ',
     +    CFF1(1,1,1)*NORM,'SHOULD BE -0.24'

 1000 FORMAT(A34,1X,1PE13.5,1X,A19)
C 
C WHEN ALL WORKS WELL THE FOLLOWING TABLE SHOULD BE OBTAINED. 
C
C  **** THE COLLISION LESS PS FLUXES 
C THE ION HEAT FLUX                 
C ION TEMPERATURE GRADIENT            -1.00000E+00     SHOULD BE -1.00
C ELECTRON TEMPERATURE GRADIENT        0.00000E+00
C ION PRESSURE GRADIENT                0.00000E+00
C ELECTRON PRESSURE GRADIENT           0.00000E+00
C 
C THE ELECTRON HEAT FLUX            
C ION TEMPERATURE GRADIENT            -1.83554E-03
C ELECTRON TEMPERATURE GRADIENT       -2.30594E+00     SHOULD BE -2.33
C ION PRESSURE GRADIENT                7.49388E-01     SHOULD BE  0.75
C ELECTRON PRESSURE GRADIENT           7.49388E-01     SHOULD BE  0.75
C 
C THE PARTICLE FLUX                 
C ION TEMPERATURE GRADIENT             4.08120E-04
C ELECTRON TEMPERATURE GRADIENT        7.49388E-01     SHOULD BE  0.75
C ION PRESSURE GRADIENT               -4.99864E-01     SHOULD BE -0.50
C ELECTRON PRESSURE GRADIENT          -4.99864E-01     SHOULD BE -0.50
C
C THESE COEFFICIENTS ARE DIRECTLY RELATED TO THE FRICTION COEFFICIENTS 
C (SEE IPP REPORT ON NEOART) THE SMALL DIFFERENCE ARE DUE TO THE FINITE
C MASS RATIO AND THE APPROXIMATION TAU(1,1) = TAU(1,2). 
C
C **** THE COLLISIONAL PS FLUXES Z = 1
C THE ION HEAT FLUX                 
C ION TEMPERATURE GRADIENT            -8.00000E-01     SHOULD BE -0.80
C ELECTRON TEMPERATURE GRADIENT        0.00000E+00
C ION PRESSURE GRADIENT                0.00000E+00
C ELECTRON PRESSURE GRADIENT           0.00000E+00
C 
C THE ELECTRON HEAT FLUX            
C ION TEMPERATURE GRADIENT             9.03527E-05
C ELECTRON TEMPERATURE GRADIENT       -1.00036E+00     SHOULD BE -0.98
C ION PRESSURE GRADIENT                2.88563E-01     SHOULD BE  0.27
C ELECTRON PRESSURE GRADIENT           2.88563E-01     SHOULD BE  0.27
C 
C THE PARTICLE FLUX                 
C ION TEMPERATURE GRADIENT            -2.76934E-04
C ELECTRON TEMPERATURE GRADIENT        2.88563E-01     SHOULD BE  0.27
C ION PRESSURE GRADIENT               -3.46683E-01     SHOULD BE -0.33
C ELECTRON PRESSURE GRADIENT          -3.46683E-01     SHOULD BE -0.33
C
C **** THE COLLISIONAL PS FLUXES Z = 2
C THE ION HEAT FLUX                 
C ION TEMPERATURE GRADIENT            -2.00000E-01
C ELECTRON TEMPERATURE GRADIENT        0.00000E+00
C ION PRESSURE GRADIENT                0.00000E+00
C ELECTRON PRESSURE GRADIENT           0.00000E+00
C 
C THE ELECTRON HEAT FLUX            
C ION TEMPERATURE GRADIENT             1.43440E-04
C ELECTRON TEMPERATURE GRADIENT       -6.26616E-01     SHOULD BE -0.64
C ION PRESSURE GRADIENT                2.29397E-01     SHOULD BE  0.23
C ELECTRON PRESSURE GRADIENT           2.29397E-01     SHOULD BE  0.23
C 
C THE PARTICLE FLUX                 
C ION TEMPERATURE GRADIENT            -2.08199E-04
C ELECTRON TEMPERATURE GRADIENT        2.29397E-01     SHOULD BE  0.23
C ION PRESSURE GRADIENT               -2.97823E-01     SHOULD BE -0.31
C ELECTRON PRESSURE GRADIENT          -2.97823E-01     SHOULD BE -0.31
C
C **** THE COLLISIONAL PS FLUXES Z = 4
C THE ION HEAT FLUX                 
C ION TEMPERATURE GRADIENT            -5.00000E-02
C ELECTRON TEMPERATURE GRADIENT        0.00000E+00
C ION PRESSURE GRADIENT                0.00000E+00
C ELECTRON PRESSURE GRADIENT           0.00000E+00
C 
C THE ELECTRON HEAT FLUX            
C ION TEMPERATURE GRADIENT             1.05994E-04
C ELECTRON TEMPERATURE GRADIENT       -4.45250E-01     SHOULD BE -0.45
C ION PRESSURE GRADIENT                1.95799E-01     SHOULD BE  0.19
C ELECTRON PRESSURE GRADIENT           1.95799E-01     SHOULD BE  0.19
C 
C THE PARTICLE FLUX                 
C ION TEMPERATURE GRADIENT            -1.29716E-04
C ELECTRON TEMPERATURE GRADIENT        1.95799E-01     SHOULD BE  0.19
C ION PRESSURE GRADIENT               -2.72713E-01     SHOULD BE -0.28
C ELECTRON PRESSURE GRADIENT          -2.72713E-01     SHOULD BE -0.28
C
C **** THE COLLISIONAL PS FLUXES Z >>1
C THE ION HEAT FLUX                 
C ION TEMPERATURE GRADIENT            -8.00000E-07
C ELECTRON TEMPERATURE GRADIENT        0.00000E+00
C ION PRESSURE GRADIENT                0.00000E+00
C ELECTRON PRESSURE GRADIENT           0.00000E+00
C 
C THE ELECTRON HEAT FLUX            
C ION TEMPERATURE GRADIENT             5.99186E-07
C ELECTRON TEMPERATURE GRADIENT       -2.51933E-01     SHOULD BE -0.25
C ION PRESSURE GRADIENT                1.52862E-01     SHOULD BE  0.15
C ELECTRON PRESSURE GRADIENT           1.52862E-01     SHOULD BE  0.15
C  
C THE PARTICLE FLUX                 
C ION TEMPERATURE GRADIENT            -6.49811E-07
C ELECTRON TEMPERATURE GRADIENT        1.52862E-01     SHOULD BE  0.15
C ION PRESSURE GRADIENT               -2.40622E-01     SHOULD BE -0.24
C ELECTRON PRESSURE GRADIENT          -2.40622E-01     SHOULD BE -0.24
C 
C THE SHOULD BE COEFFICIENTS ARE FROM THE PAPER OF HAZELTINE AND HINTON
C PHYS FLUIDS 16, 1883, (1973). THE NORMALIZATION OF THE FLUXES IS SUCH
C THAT THE COEFFICIENTS IN EQS. (40-42) OF THIS PAPER ARE OBTAINED.
C
      RETURN 
      END
